apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  POSTGRES_SERVER: {{ .Values.db.env.POSTGRES_SERVER | quote }}
  POSTGRES_PORT: {{ .Values.db.env.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.db.env.POSTGRES_DB | b64enc }}
  POSTGRES_USER: {{ .Values.db.env.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.env.POSTGRES_PASSWORD | b64enc }}
  SECRET_KEY: {{ .Values.backend.env.SECRET_KEY | b64enc }}
  FIRST_SUPERUSER: {{ .Values.backend.env.FIRST_SUPERUSER | b64enc }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.backend.env.FIRST_SUPERUSER_PASSWORD | b64enc }}
  SMTP_USER: {{ .Values.backend.env.SMTP_USER | default "" | b64enc }}
  SMTP_PASSWORD: {{ .Values.backend.env.SMTP_PASSWORD | default "" | b64enc }} 