name: Add to Project

# -------------  DESACTIVADO TEMPORALMENTE  -------------
# Quita “if: false” (o cámbialo a “if: github.event_name != 'pull_request'”)
# cuando quieras volver a activar el job.
# -------------------------------------------------------

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    if: false            # ← desactiva el job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/fastapi/projects/2
          github-token: ${{ secrets.PROJECTS_TOKEN }}
